# Configuration site theme
theme:
  name: material
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: './images/logo-theeye-circle.png'
  favicon: './images/logo-theeye-docu-glasses.png'
markdown_extensions:
  - codehilite

# Project information
site_name: 'TheEye'
site_description: 'TheEye is a platform for Robot automation Processes and Systems'
site_url: 'https://app.theeye.io/dashboard'

# Menu
nav:
- Home: 'index.md'
- First steps: 'first-steps.md'
- Core concepts:
    - JSON: './core-concepts/json.md'
    - Resources: './core-concepts/index.md'
    - Alerts and Notifications: './core-concepts/alerts-and-notifications.md'
    - Indicators: './core-concepts/indicators.md'
    - Monitors: './core-concepts/monitors.md'
    - Tasks:
        - Basics: './core-concepts/tasks/index.md'
        - Triggers: './core-concepts/tasks/triggers.md'
        - Workflows: './core-concepts/tasks/workflows.md'
        - Types:
          - Notification: './core-concepts/tasks/notification_type.md'
          - Script: './core-concepts/tasks/script_type.md'
    - Templates: './core-concepts/templates.md'
    - Webhooks: './core-concepts/webhooks.md'
    - Scripts:
        - Working with Scripts: './core-concepts/scripts/index.md'
        - Run as...: './core-concepts/scripts/runas.md'
        - Write: './core-concepts/scripts/write.md'
- Bot Agent:
    - Installation: './core-concepts/the-eye-agent/index.md'
    - Source Code: './core-concepts/the-eye-agent/sources_install.md'
    - Binary build: './core-concepts/the-eye-agent/binary_build.md'
    - Setup: './core-concepts/the-eye-agent/setup.md'
    - Debug: './core-concepts/the-eye-agent/debug.md'
    - Raspberry: './core-concepts/the-eye-agent/raspberry.md'
    - Services in Linux:
        - Example init.d: './core-concepts/the-eye-agent/examples/etc_init.d_theeye-agent'
        - Example systemd: './core-concepts/the-eye-agent/examples/etc_systemd_system_theeye-agent.service'
- User management: 'user-management.md'
- Integrations:
    - AWS: './integrations/aws/index.md'
    - ELK: './integrations/elk/index.md'
    - Kubernetes: './integrations/kubernetes/index.md'
    - API for developers:
        - Enable access to APIs: './integrations/api/index.md'
        - Indicators: './integrations/api/api_resources_indicator.md'
        - Tasks: './integrations/api/api_resources_task.md'
        - Monitors: './integrations/api/api_resources_monitor.md'
- Assets:
    - Recipes: './assets/recipes/index.md'
    - Scripts: './assets/scripts/index.md'
- CLI: './cli.md'
- Support: './support.md'
- FAQ's: './faqs_pages/index.md'
- About:
    - About us: './about/index.md'
    - Terms and Conditions: './about/terms.md'

# Footer
copyright: 'TheEye.io | Copyright &copy; 2019 - All rights reserved'
extra:
  social:
    - type: 'medium'
      link: 'https://medium.com/@theeye_io'
    - type: 'facebook'
      link: 'https://www.facebook.com/theeyeio/'
    - type: 'twitter'
      link: 'https://twitter.com/theeye_io'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/theeye.io/'
