# Configuration site theme
theme:
  name: material
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: './images/logo-theeye-circle.png'
  favicon: './images/logo-theeye-docu-glasses.png'

markdown_extensions:
  - codehilite

# Project information
site_name: 'TheEye'
site_description: 'TheEye is a platform for Robot automation Processes and Systems'
site_url: 'https://app.theeye.io/dashboard'

# Menu
nav:
  - Home: 'index.md'
  - First steps: 'first-steps.md'
  - Core concepts:
    - Bot Agent:
      - Installation: './core-concepts/agent/index.md'
      - Source Code: './core-concepts/agent/sources_install.md'
      - Binary build: './core-concepts/agent/binary_build.md'
      - Setup: './core-concepts/agent/setup.md'
      - Debug:
        - Unix: './core-concepts/agent/debug-unix.md'
        - Windows: './core-concepts/agent/debug-windows.md'
      - Raspberry: './core-concepts/agent/raspberry.md'
      - Services in Linux:
        - Example init.d: './core-concepts/agent/examples/etc_init.d_theeye-agent'
        - Example systemd: './core-concepts/agent/examples/etc_systemd_system_theeye-agent.service'
    - JSON: './core-concepts/json.md'
    - Events: './core-concepts/events.md'
    - Tasks:
      - Basics: './core-concepts/tasks/index.md'
      - Triggers: './core-concepts/tasks/triggers.md'
      - Workflows: './core-concepts/tasks/workflows.md'
      - Types:
        - Notification: './core-concepts/tasks/notification_type.md'
        - Script: './core-concepts/tasks/script_type.md'
    - Alerts and Notifications: './core-concepts/alerts-and-notifications.md'
    - Indicators: './core-concepts/indicators.md'
    - Monitors: './core-concepts/monitors.md'
    - Templates: './core-concepts/templates.md'
    - Webhooks: './core-concepts/webhooks.md'
    - Scripts:
      - Definitions: './core-concepts/scripts/index.md'
      - Run as...: './core-concepts/scripts/runas.md'
      - Write: './core-concepts/scripts/write.md'
    - IAM:
      - User Management: './core-concepts/iam/user-management.md'
      - Logical Access: './core-concepts/iam/logical_access.md'
  - Integrations:
    - Logger: './integrations/logger/index.md'
    - AWS: './integrations/aws/index.md'
    - ELK: './integrations/elk/index.md'
    - Kubernetes: './integrations/kubernetes/index.md'
  - API for developers:
    - Enable access to APIs: './api/auth.md'
    - Indicators: './api/indicators/index.md'
    - Tasks:
      - Basics: './api/tasks/index.md'
      - Arguments: './api/tasks/arguments.md'
    - Monitors: './api/monitors/index.md'
    - Jobs:
      - Basics: './api/jobs/index.md'
    - Webhooks: './api/webhooks/index.md'
    - Sync: './api/sync/index.md'
  - Assets:
    - Recipes: './assets/recipes/index.md'
    - Scripts: './assets/scripts/index.md'
  - CLI: './cli.md'
  - Support:
    - Home: './support/index.md'
    - Http Server: './support/http_server_discovery.md'
    - Troubleshooting: './support/troubleshooting.md'
  - FAQ's: './faqs_pages/index.md'
  - About:
    - About us: './about/index.md'
    - Terms and Conditions: './about/terms.md'

# Footer
copyright: 'TheEye.io | Copyright &copy; 2019 - All rights reserved'
extra:
  social:
    - type: 'medium'
      link: 'https://medium.com/@theeye_io'
    - type: 'facebook'
      link: 'https://www.facebook.com/theeyeio/'
    - type: 'twitter'
      link: 'https://twitter.com/theeye_io'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/theeye.io/'
